### PR TITLE
Fix script fail on configuration files changes prompt

### PR DESCRIPTION
**Pull request by aseemrb**
Fixes the script failure on prompts for confirming changes in configuration files #8

### CODE REVIEW

**Comment by FrankSzn** [comment]
After using the new provision.sh , the installation has another problem "Unable to locate package os161-toolchain"

**Comment by aseemrb** [comment]
@FrankSzn which operating system are you using? Were you able to locate the package with the original provision.sh?

**Comment by FrankSzn** [comment]
os x 10.1
it just give me the error"default: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/universe/source/Sources  Hash Sum mismatch"
I just copy the text of your provision.sh and paste to the old one,nothing else

**Comment by aseemrb** [comment]
Please refer to [this](http://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error).
Also, I see that the URL http://security.ubuntu.com/ubuntu/dists/trusty-security/universe/source/Sources actually gives a 404.
The new provision script has changed nothing to the apt packages and updates/upgrades, so this is a singular problem, a special case maybe, you could try setting things up all over again afresh.

**Comment by FrankSzn** [comment]
Thanks!That's the problem caused for the network in china,after using the vpn,problem is solved!

**Comment by kylethebaker** [comment]
Seconding this. I also had to patch this in to get everything set up correctly, otherwise provisioning doesn't make it very far.

**Comment by gchallen** [comment]
We've changed the Vagrantfile to use a pre-rolled box, so this shouldn't be a problem any more. Thanks!

**Pull request closed without merging**
